apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2018-02-22T23:50:41Z
    generation: 7
    labels:
      run: nginx
      enviroment: desenvolvimento
      appname: nginxdev
      dc: USA
    name: nginxdev
    namespace: default
    resourceVersion: "41145"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginxdev
    uid: 30934873-182b-11e8-911e-42010a80000b
  spec:
    replicas: 5
    selector:
      matchLabels:
        run: nginx
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: nginx
          DC: USA
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          volumeMounts:
          - name: nfs-vol
            mountPath: /usr/share/nginx/html
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nfs-vol
          persistentVolumeClaim:           
            claimName: pvc-exercice
        nodeSelector:
            dc: USA
  status:
    availableReplicas: 6
    conditions:
    - lastTransitionTime: 2018-02-23T00:14:06Z
      lastUpdateTime: 2018-02-23T00:14:06Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 7
    readyReplicas: 5
    replicas: 5
    updatedReplicas: 5
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
