apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-02-23T00:20:27Z
  labels:
    run: nginx
  name: nginxprod
  namespace: default
  resourceVersion: "41645"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 59047f53-182f-11e8-b380-42010a80000b
spec:
  clusterIP: 10.105.155.36
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
